version: "3.9"
services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  backend:
    image: sg_bus_api
    build: .
    container_name: sg_bus_api_1
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      API_KEY: 0CJCe167TYqoXZrnj6XT4Q==
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"